CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "system_config" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "field" varchar(255),
                                 "value" text,
                                 "note" text
);

CREATE TABLE "subscription" (
                                "id" varchar(50) PRIMARY KEY,
                                "subscription_name" varchar(255) NOT NULL,
                                "level" int NOT NULL,
                                "description" text,
                                "price_per_month" decimal,
                                "price_per_year" decimal,
                                "supported_features" text,
                                "gpt_model" varchar(50) NOT NULL,
                                "gpt_limit" int NOT NULL,
                                "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "image" (
                         "fe_image_name" varchar(255) PRIMARY KEY,
                         "s3_image_name" varchar(255),
                         "gg_image_link" varchar(255),
                         "created_at" timestamp,
                         "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "users" (
                         "id" uuid PRIMARY KEY,
                         "email" varchar(255) NOT NULL,
                         "full_name" varchar(255) NOT NULL,
                         "password" text,
                         "avatar_id" varchar(255),
                         "created_at" timestamp,
                         "updated_at" timestamp,
                         "role" varchar(50) NOT NULL DEFAULT 'STUDENT',
                         "earned_money" decimal NOT NULL DEFAULT 0,
                         "gpt_remaining_usage" int NOT NULL DEFAULT 0,
                         "theme" varchar(50) NOT NULL DEFAULT 'DEFAULT',
                         "status" varchar(50) NOT NULL,
                         "enabled" boolean NOT NULL DEFAULT false
);

CREATE TABLE "referral_code" (
                                 "user_id" uuid PRIMARY KEY,
                                 "code" varchar(255) NOT NULL,
                                 "reference_number" int NOT NULL DEFAULT 0,
                                 "using_referral_code" boolean NOT NULL DEFAULT false
);

CREATE TABLE "user_subscription" (
                                     "user_id" uuid PRIMARY KEY,
                                     "subscription_id" varchar(50),
                                     "paid_type" varchar(50) NOT NULL,
                                     "expired_datetime" timestamp
);

CREATE TABLE "transaction" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "user_id" uuid,
                               "amount" decimal NOT NULL,
                               "content" text,
                               "created_at" timestamp
);

CREATE TABLE "upgrade_request" (
                                   "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "user_id" uuid NOT NULL,
                                   "paid_type" varchar(50) NOT NULL,
                                   "price" decimal NOT NULL,
                                   "created_at" timestamp,
                                   "status" varchar(50) NOT NULL DEFAULT 'PENDING'
);

CREATE TABLE "study_set" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "study_set_name" varchar(255) NOT NULL,
                             "image_id" varchar(255),
                             "user_id" uuid,
                             "created_at" timestamp,
                             "updated_at" timestamp,
                             "visibility" varchar(50) NOT NULL DEFAULT 'PUBLIC',
                             "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "questions" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "question" text NOT NULL,
                             "answers" text[] NOT NULL,
                             "correct_answer" text,
                             "is_gpt_generated" boolean NOT NULL DEFAULT false,
                             "full_gpt_answer" text,
                             "study_set_id" int NOT NULL
);

CREATE TABLE "user_question_note" (
                                      "user_id" uuid,
                                      "question_id" int,
                                      "note" text NOT NULL ,
                                      PRIMARY KEY ("user_id", "question_id")
);

CREATE TABLE "pomodoro" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "user_id" uuid,
                            "study_time" int NOT NULL DEFAULT 1500,
                            "short_break" int NOT NULL DEFAULT 300,
                            "long_break" int NOT NULL DEFAULT 900,
                            "long_break_interval" int NOT NULL DEFAULT 4,
                            "learning_method" varchar(50),
                            "status" varchar(50) NOT NULL DEFAULT 'ON'
);

CREATE TABLE "gpt_message" (
                               "id" uuid PRIMARY KEY,
                               "user_id" uuid,
                               "content" text,
                               "gpt_answer" text,
                               "created_at" timestamp
);

CREATE TABLE "book" (
                        "id" uuid PRIMARY KEY,
                        "name" varchar(255) NOT NULL,
                        "link" text,
                        "status" boolean NOT NULL DEFAULT true
);


ALTER TABLE "users" ADD FOREIGN KEY ("avatar_id") REFERENCES "image" ("fe_image_name");

ALTER TABLE "user_subscription" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_subscription" ADD FOREIGN KEY ("subscription_id") REFERENCES "subscription" ("id");

ALTER TABLE "transaction" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "upgrade_request" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "study_set" ADD FOREIGN KEY ("image_id") REFERENCES "image" ("fe_image_name");

ALTER TABLE "study_set" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "questions" ADD FOREIGN KEY ("study_set_id") REFERENCES "study_set" ("id");

ALTER TABLE "user_question_note" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_question_note" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");

ALTER TABLE "pomodoro" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "gpt_message" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "referral_code" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE INDEX IF NOT EXISTS idx_users_email on users(email);

CREATE INDEX IF NOT EXISTS idx_referral_code_code on referral_code(code);

CREATE INDEX IF NOT EXISTS idx_image_s3_image_name on image(s3_image_name);

CREATE INDEX IF NOT EXISTS idx_study_set_name on study_set(study_set_name);

insert into subscription (id, subscription_name, level, price_per_month, price_per_year, supported_features, gpt_model, gpt_limit)
values
    ('BASIC', 'Basic plan', 1, 0, 0, '10 study sets;Full learning methods;Pomodoro supported;GPT 3.5 model supported;With ads;Only online available;', '3.5', 30),
    ('PRO', 'Pro plan', 2, 79000, 799000, 'Unlimited personal study sets;Full Learning methods;Pomodoro supported;GPT 3.5 model supported;No ads;Offline mode for mobile;Personal customization', '3.5', 100);

insert into users (id, email, full_name, created_at, updated_at, role, status, enabled)
values (uuid_generate_v4(), 'persai.work@gmail.com', 'Persai admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ADMIN', 'SUCCEED', true);
